name: ServerUtilities
version: '1.0.0'
main: dev.kodysimpson.serverutilities.ServerUtilities
description: Simple Paper commands for Part 5 of Make a Minecraft Plugin in 2026.
author: KodySimpson
api-version: '26.2'
